source "http://rubygems.org"

gem 'sinatra'
gem 'thin'
gem 'mongo'
gem 'mongoid'
gem 'bson_ext'
gem 'json'
gem 'haml'
gem 'redcarpet'
gem 'sparql-client'
gem 'linkeddata'

group :development, :test  do
  gem 'rspec'
  gem 'rack-test'
  gem 'sinatra-contrib'
  gem 'database_cleaner'
end

