import "#{`bundle show mongoid`.strip}/lib/mongoid/railties/database.rake"
require_relative 'db/seeds'

task :environment do
  require './app'
end

namespace :db do
  desc "Drop db data"
  task :drop => :environment do
    Seeds.new.drop
  end

  desc "Seed db data"
  task :seed => :environment do
    Seeds.new.seed_all
  end

  desc "Test Seed"
  task :test_seed => :environment do
    Seeds.new.seed_test
  end
end

desc "Run those specs"
task :spec do
  require "rspec/core/rake_task"
  RSpec::Core::RakeTask.new(:spec) do |t|
    t.rspec_opts = %w{--colour --format documentation}
  end
end

