import "#{`bundle show mongoid`.strip}/lib/mongoid/railties/database.rake"

task :environment do
  require './app'
end

namespace :db do
  desc "Drop db data"
  task :drop => :environment do
    Site.destroy_all
    MonthlyData.destroy_all
  end

  desc "Seed db data"
  task :seed => :environment do
    require_relative 'db/seeds'
  end

  desc "Test Seed"
  task :test_seed => :environment do
    require_relative 'db/test_seeds'
  end
end

desc "Run those specs"
task :spec do
  require "rspec/core/rake_task"
  RSpec::Core::RakeTask.new(:spec) do |t|
    t.rspec_opts = %w{--colour --format documentation}
  end
end

